services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
networks:
  postgres:
    driver: bridge

volumes:
  postgres: