server:
  port: 8080
spring:
  application:
    name: Two Factor Authentication & JWT
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db.migration
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # a day